<?php $this->headScript()->prependFile($this->baseUrl() . '/js/teacher.index.js'); ?>

<div class="center">
    <?php if ($this->conferencesAvailable) { ?>
        <h2><?php echo htmlentities($this->conferenceName) ?></h2>
        <p class="breadcrumb">Home</p>
        <p class="justify">Welkom op de oudercontacten applicatie van DBZ.</p>
        <?php if ($this->titularConference || $this->teacherConference) { ?>
            <table class="table">
                <tr>
                    <th>Oudercontact</th>
                    <th>data</th>
                    <th>start inschrijving</th>
                    <th>einde inschrijving</th>
                    <th>&nbsp;</th>
                </tr>
                <?php if ($this->titularConference) { ?>
                    <tr>
                        <td>Klassenleraren</td>
                        <td><?php echo htmlentities($this->days1) ?></td>
                        <td><?php echo htmlentities($this->start1) ?></td>
                        <td><?php echo htmlentities($this->end1) ?></td>
                        <td><a href="<?php echo $this->url(array('controller' => 'Teacher', 'action' => 'appointment', 'tiid' => $this->staffId), null, true) ?>" class="btn btn-info">Bekijk uw agenda</a></td>
                    </tr>
                <?php } ?>
                <?php if ($this->teacherConference) { ?>
                    <tr>
                        <td>Vakleerkrachten</td>
                        <td><?php echo htmlentities($this->days2) ?></td>
                        <td><?php echo htmlentities($this->start2) ?></td>
                        <td><?php echo htmlentities($this->end2) ?></td>
                        <td><a href="<?php echo $this->url(array('controller' => 'Teacher', 'action' => 'appointment', 'teid' => $this->staffId), null, true) ?>" class="btn btn-info">Bekijk uw agenda</a></td>
                    </tr>
                <?php } ?>
            </table>
            <div id="alertMore" class="alert alert-info">
                <a id="lnkClose"class="close">&times;</a>
                <p class="justify">Inschrijvingen voor beide onderdelen van dit oudercontact verlopen via deze applicatie. Bovenstaand vindt u de start- en einddatum voor deze inschrijvingen. Als leerkracht kunt u voor de start van de inschrijvingen aanduiden op welke contactdagen u aanwezig zult zijn. Dit kunt u doen via uw agenda en daar de gewenste dagen selecteren.</p>
                <p class="justify">Verder kunt u hier uw agenda met gemaakte afspraken bekijken en zelf pauzes toevoegen op de gewenste plaatsen. Indien u het start- of eindtijdstip van uw agenda wilt aanpassen kunt u zicht richten tot de administratie.</p>
            </div>
            <p><a id="lnkMore" href="<?php echo $this->url(array('controller' => 'Teacher', 'action' => 'index', 'info' => 'more'), null, true) ?>">Meer info</a></p>
        <?php } else {?>
            <div class="alert alert-info">
                <p>U bent geen titularis of vakleerkracht van een klasgroep waarvoor dit oudercontact wordt georganiseerd.</p>
            </div>
        <?php } ?>
    <?php } else { ?>
        <h2>Oudercontacten</h2>
        <div class="alert alert-info">
            <p>Er zijn momenteel geen oudercontacten georganiseerd.</p>
        </div>
    <?php } ?>
</div>