<?php $this->headScript()->prependFile($this->baseUrl() . '/js/admin.administer.js'); ?>

<div class="center">
    <h2>Rechten beheer</h2>
    <p class="breadcrumb"><a href="<?php echo $this->url(array('controller' => $this->controller), null, true) ?>">Home</a> > Rechten beheer</p>
    <?php if ($this->accessebilityLevel == 1) { ?>
        <form action="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'administer'), null, true) ?>" method="post" class="large">
            <table id="rightsTable" class="table table-striped tablesorter">
                <thead>
                    <tr>
                        <th>Personeelslid</th>
                        <th>Rechten</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->staffRights as $staffRight) { ?>
                        <tr>
                            <td><label for="staff<?php echo htmlentities($staffRight->getStaffId()) ?>"><?php echo htmlentities($staffRight->getFirstname() . ' ' . $staffRight->getName()) ?></label></td>
                            <td>
                                <select id="staff<?php echo htmlentities($staffRight->getStaffId()) ?>" name="staff<?php echo htmlentities($staffRight->getStaffId()) ?>" class="large">
                                    <option value="1" <?php echo ($staffRight->getAccessebilityLevel() == 1 ? 'selected="selected"' : '') ?>>Beheerderstoegang hoogste niveau</option>
                                    <option value="2" <?php echo ($staffRight->getAccessebilityLevel() == 2 ? 'selected="selected"' : '') ?>>Beheerderstoegang laagste niveau</option>
                                    <option value="0" <?php echo ($staffRight->getAccessebilityLevel() == 0 ? 'selected="selected"' : '') ?>>Geen beheerderstoegang</option>
                                </select>
                            </td>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
            <div id="pager" class="pager">
                <p>
                    <a class="prev btn">Vorige</a>
                    <input class="pagedisplay" type="text" disabled="disabled">
                    <a class="next btn">Volgende</a>
                    <select class="pagesize">
                        <option value="10" selected="selected">10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                    </select>
                </p>
            </div>
            
            <input type="submit" class="btn btn-primary" id="btnSave" name="btnSave" value="Bewaren" />
            <input type="submit" class="btn" name="btnCancel" value="Annuleren" />
        </form>
    <?php } else { ?>
        <div class="alert alert-info">
            <p>U heeft onvoldoende rechten om de rechten van andere personen te configureren.</p>
        </div>
    <?php }?>
</div>