<?php $this->headScript()->prependFile($this->baseUrl() . '/js/admin.appointmentedit.js'); ?>

<div class="center">
  <h2>
    <?php echo ($this->titular ? 'Klassenleraar' : 'Vakleerkracht') .
      ': ' . htmlentities($this->name, ENT_NOQUOTES, 'utf-8'); ?>
  </h2>
  <p class="breadcrumb">
    <a href="<?php echo $this->url(array('controller' => $this->controller), null, true) ?>">Home</a> 
    &gt; <a href="<?php echo $this->url(array('controller' => $this->controller, 'action' => 'appointment'), null, true) ?>">Planning</a> > <?php echo ($this->titular ? 'Klassenleraren' : 'Vakleerkrachten'); ?></p>
  <div class="printOnly">
    <h2>Agenda <?php echo ($this->titular ? 'klassenleraar' : 'vakleerkracht') .
        ': ' . htmlentities($this->name, ENT_NOQUOTES, 'utf-8'); ?></h2>
  </div>
  <div class="modal" id="confirm">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4>Afspraak verwijderen</h4>
      </div>
      <div class="modal-body">
        <p>U heeft aangeduid dat u een afspraak &quot;<span id="detail"></span>&quot; 
          wilt verwijderen. Weet u zeker dat u deze afspraak wilt verwijderen?</p>
      </div>
      <div class="modal-footer">
        <a href="#" id="cancel" class="btn">Annuleren</a>
        <a href="#" id="confirmed" class="btn btn-danger">Verwijderen</a>
      </div>
    </div>
  <div class="tabbable">
    <ul class="nav nav-tabs">
      <?php foreach ($this->days as $day) { ?>
        <li <?php if ($this->activeId == $day->getDayId()) echo'class="active"'; ?>>
          <a href="#d<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
             data-toggle="tab">
               <?php echo htmlentities(DateUtilities::weekday(strtotime($day->getDay()), true) .
                       ' ' . date('d ', strtotime($day->getDay())) .
                       DateUtilities::month(strtotime($day->getDay()), true), ENT_NOQUOTES, 'utf-8'); ?>
          </a>
        </li>
      <?php } ?>
    </ul>
    <form 
      action="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-edit', 'succes' => '')) ?>" 
      method="post">
    <div class="tab-content">
      <?php if($this->roomErr) { ?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&times;</a>
          <p><strong>Oeps!</strong> U heeft geen lokaal geselecteerd voor dit contact.</p>
        </div>
      <?php } ?>
      <?php if($this->startErr) { ?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&times;</a>
          <p><strong>Oeps!</strong> U heeft een ongeldig startuur ingevuld voor dit contact.</p>
        </div>
      <?php } ?>
      <?php if($this->endErr) { ?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&times;</a>
          <p><strong>Oeps!</strong> 
            U heeft een ongeldig einduur ingevuld voor dit contact.</p>
        </div>
      <?php } ?>
      <?php if($this->saved) { ?>
        <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <p>De instellingen werden succesvol bewaard.</p>
        </div>
      <?php } ?>
      <?php if($this->status == "errorP") { ?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&times;</a>
          <p>De afspraak werd niet gemaakt omdat de ouders op dit tijdstip 
            reeds een andere afspraak hebben.</p>
        </div>
      <?php } ?>
      <?php if($this->status == "error") { ?>
        <div class="alert alert-error">
          <a class="close" data-dismiss="alert">&times;</a>
          <p>De afspraak werd niet gemaakt omdat de leerkracht op dit tijdstip 
            reeds een andere afspraak heeft.</p>
        </div>
      <?php } ?>
      <?php if($this->status == "succes") { ?>
        <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <p>De afspraak werd succesvol bewaard.</p>
        </div>
      <?php } ?>
        
      <?php foreach ($this->days as $day) { ?>
        <div class="tab-pane <?php if ($this->activeId == $day->getDayId()) echo'active'; ?>" 
             id="d<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>">
          <p><a class="settingsDisplay" href="#">Instellingen...</a></p>

          <dl class="settings">
            <dt><label>Aanwezig: </label></dt>
            <dd><input type="checkbox" 
                       name="present<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
                       value="true" <?php echo ($day->isPresent() ? 'checked="checked"' : '') . ($day->isObligated() || !$this->settingsEnabled ? ' readonly="readonly"' : ''); ?>/>
            </dd>
            <dt><label>Lokaal:</label></dt>
            <dd>
              <select id="room<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
                      name="room<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>">
                <option value="0">Kies een beschikbaar lokaal...</option>
                <?php foreach ($day->getAvailableRooms() as $room) { ?>
                  <option value="<?php echo htmlentities($room->getRoomId(), ENT_NOQUOTES, 'utf-8') ?>" 
                    <?php if ($day->getRoomId() == $room->getRoomId()) echo 'selected="selected"' ?>>
                      <?php echo htmlentities($room->getName(), ENT_NOQUOTES, 'utf-8')?>
                  </option>
                <?php } ?>
              </select>
            </dd>
            <dt><label>Start:</label></dt>
            <dd><input type="text" 
                       id="start<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
                       name="start<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
                       value="<?php echo htmlentities($day->getStart(), ENT_NOQUOTES, 'utf-8') ?>" 
                         <?php echo ($this->settingsEnabled ? '' : 'disabled="disabled"') ?> /> (hh:mm)</dd>
            <dt><label>Einde:</label></dt>
            <dd><input type="text" 
                       id="end<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
                       name="end<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" 
                       value="<?php echo htmlentities($day->getEnd(), ENT_NOQUOTES, 'utf-8') ?>" 
                         <?php echo ($this->settingsEnabled ? '' : 'disabled="disabled"') ?> /> (hh:mm)</dd>
            <dd>
              <input type="hidden" 
                     name="days[]" 
                     value="<?php echo htmlentities($day->getDayId(), ENT_NOQUOTES, 'utf-8') ?>" />
              <input type="submit" 
                     class="btn btn-primary" name="btnSave" value="Bewaren" />
              <input type="submit" 
                     class="btn" name="btnCancel" value="Annuleren" />
            </dd>
          </dl>

          <?php if ($day->isPresent()) { ?>
            <table class="table table-striped table-condensed">
              <tr class="printOnly">
                <th colspan="3">
                  <?php echo ucfirst(htmlentities(
                          DateUtilities::weekday(strtotime($day->getDay()), false) .
                          ' ' . date('d ', strtotime($day->getDay())) . 
                          DateUtilities::month(strtotime($day->getDay()), false), ENT_NOQUOTES, 'utf-8')); ?>
                  <?php echo ($this->roomName != null ? ': ' . htmlentities($this->roomName, ENT_NOQUOTES, 'utf-8') : '') ?>
                </th>                
              </tr>
              <?php $time = strtotime($day->getStart());
                $pointer = 0;
                $appointment = $day->getAppointments();
                while ($time < strtotime($day->getEnd())) {
              ?>
                <tr>
                  <td class="hours"><?php echo Date('H:i', $time) ?></td>
                  <?php if ($pointer >= sizeof($appointment)) { ?>
                    <td class="larger">&nbsp;</td>
                    <td class="icons">
                      <a href="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-new', 'time' => Date('H:i', $time), 'dayId' => $day->getDayId(), 'staffId' => $this->staffId)); ?>">
                        <i class="icon-user"><span class="tooltip" data-original-title="Afspraak invoeren"></span></i>
                      </a>
                      <a href="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-new', 'time' => Date('H:i', $time), 'dayId' => $day->getDayId(), 'staffId' => $this->staffId, 'break' => 'true')); ?>">
                        <i class="icon-time"><span class="tooltip" data-original-title="Pauze invoeren"></span></i>
                      </a>
                    </td>
                  <?php }
                  else {
                    $slot = $appointment[$pointer]->getAppointment();
                    if (strtotime($slot) == $time) {
                      if ($appointment[$pointer]->getPupilId() != null && $appointment[$pointer]->getParentId() != null) {
                        $pupil = Application_Model_DbTable_Pupils::getPupilById($appointment[$pointer]->getPupilId());
                        $parent = Application_Model_DbTable_Parents::getParentByParentId($appointment[$pointer]->getParentId());
                        $group = Application_Model_DbTable_Groups::getGroupByGroupId($pupil->getGroupId());
                        $course = ($appointment[$pointer]->getCourseId() != null ? Application_Model_DbTable_Courses::getCourseById($appointment[$pointer]->getCourseId()) : null);?>
                        <td class="larger"><?php echo $pupil->getFirstname() . 
                                ' ' . $pupil->getName() . ' - ' . 
                                $parent->getSalutation() . ' (' . 
                                $group->getName() . 
                                ($course!= null ? ' - ' . $course->getCourse() : '') . ')'; ?>
                        </td>
                        <td class="icons">
                          <a href="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-delete', 'appointmentId' => $appointment[$pointer]->getAppointmentId(), 'activeId' => $day->getDayId())); ?>" class="sure">
                            <i class="icon-trash">
                              <span class="tooltip" 
                                    data-original-title="Afspraak verwijderen">                                
                              </span>
                            </i>
                          </a>
                        </td>
                        <?php $pointer++;
                      }
                      else { ?>
                        <td class="larger">Pauze</td>
                        <td class="icons">
                          <a href="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-delete', 'appointmentId' => $appointment[$pointer]->getAppointmentId(), 'activeId' => $day->getDayId())); ?>" class="sure">
                            <i class="icon-trash"><span class="tooltip" data-original-title="Pauze verwijderen"></span></i></a>
                        </td>
                        <?php $pointer++;
                      }
                    }
                    else { ?>
                      <td class="larger">&nbsp;</td>
                      <td class="icons">
                        <a href="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-new', 'time' => Date('H:i', $time), 'dayId' => $day->getDayId(), 'staffId' => $this->staffId)); ?>">
                          <i class="icon-user"><span class="tooltip" data-original-title="Afspraak invoeren"></span></i></a>
                        <a href="<?php echo $this->url(array('controller' => 'Admin', 'action' => 'appointment-new', 'time' => Date('H:i', $time), 'dayId' => $day->getDayId(), 'staffId' => $this->staffId, 'break' => 'true')); ?>">
                          <i class="icon-time"><span class="tooltip" data-original-title="Pauze invoeren"></span></i></a>
                      </td>
                    <?php }
                  }?>
                </tr>
                <?php
                $time += $this->timeslotLength;
              } ?>
            </table>
            <a href="#" class="btn btnPrint"><i class="icon-print"></i> Print agenda</a>
          <?php }
          else { ?>
            <div class="alert alert-info">
              <p><?php echo htmlentities($this->name, ENT_NOQUOTES, 'utf-8') ?> 
                is niet aanwezig vandaag en heeft bijgevolg geen afspraken.</p>
            </div>
          <?php } ?>
        </div>
      <?php } ?>
    </div>
    </form>
  </div>
</div>